# Generated by Django 3.2.3 on 2022-06-25 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_newuser_user_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newuser',
            name='name',
        ),
    ]
