# Generated by Django 3.2 on 2022-07-04 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_newuser_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='newuser',
            name='otp',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
