# Generated by Django 3.2 on 2022-07-04 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_newuser_otp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newuser',
            name='otp',
        ),
    ]
