# Generated by Django 3.2.3 on 2021-07-19 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='location',
            new_name='alternative_phone',
        ),
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='town',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='shipping_price',
            new_name='shipping_fee',
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='estate',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='landmark',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='phone',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='road',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
