# Generated by Django 3.2.3 on 2021-07-19 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20210719_1113'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='Image',
            new_name='name',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
