# Generated by Django 3.2.3 on 2021-08-05 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20210804_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='index.jpg', null=True, upload_to='images/'),
        ),
    ]
