# Generated by Django 3.2.3 on 2021-07-19 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20210719_2026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('mpesa', 'mpesa'), ('cash_on_delevery', 'cash_on_delevery'), ('equity', 'equity'), ('kcb', 'kcb'), ('paypal', 'paypal')], max_length=200, null=True),
        ),
    ]
