# Generated by Django 3.2.3 on 2021-08-05 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='index.jpg', null=True, upload_to=''),
        ),
    ]
