# Generated by Django 3.2.3 on 2021-08-20 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_topproducts'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TopProducts',
            new_name='CaroselItems',
        ),
    ]
