# Generated by Django 3.2.3 on 2021-07-21 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_alter_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('mpesa', 'mpesa'), ('ondelevery', 'ondelevery')], max_length=200, null=True),
        ),
    ]
