# Generated by Django 3.2.3 on 2021-08-24 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_auto_20210820_1924'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tag',
            new_name='Room',
        ),
        migrations.RemoveField(
            model_name='product',
            name='tag',
        ),
        migrations.AddField(
            model_name='product',
            name='room',
            field=models.ManyToManyField(blank=True, null=True, to='store.Room'),
        ),
    ]
