# Generated by Django 3.2.3 on 2021-09-15 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_auto_20210824_2058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('mpesa', 'mpesa'), ('ondelivery', 'ondelivery')], max_length=200, null=True),
        ),
    ]
