# Generated by Django 3.2.3 on 2022-06-24 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_auto_20220624_0119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchquery',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
