# Generated by Django 3.2.3 on 2022-06-24 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_alter_searchquery_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchquery',
            name='time',
            field=models.TimeField(auto_now_add=True, null=True),
        ),
    ]
