# Generated by Django 3.2.3 on 2022-06-24 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0019_searchquery_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchquery',
            name='date',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='searchquery',
            name='time',
            field=models.TimeField(auto_now=True, null=True),
        ),
    ]
