# Generated by Django 3.2.3 on 2022-06-24 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0021_auto_20220624_0144'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SearchQuery',
            new_name='QuerySearched',
        ),
        migrations.AlterModelOptions(
            name='querysearched',
            options={'ordering': ('name',)},
        ),
        migrations.RenameField(
            model_name='querysearched',
            old_name='query',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='product',
            name='searchquery',
        ),
        migrations.AddField(
            model_name='product',
            name='querysearched',
            field=models.ManyToManyField(blank=True, null=True, to='store.QuerySearched'),
        ),
    ]
