export const  PRODUCT_CAROSEL_REQUEST =    'PRODUCT_CAROSEL_REQUEST'
export const  PRODUCT_CAROSEL_SUCCESS =    'PRODUCT_CAROSEL_SUCCESS'
export const  PRODUCT_CAROSEL_FAIL    =    'PRODUCT_CAROSEL_FAIL'