export const CATEGORIES_LIST_REQUEST = 'CATGORIES_REQUEST_SUCCESS'
export const CATEGORIES_LIST_SUCCESS = 'CATGORIES_LIST_SUCCESS'
export const CATEGORIES_LIST_FAIL = 'CATGORIES_LIST_FAIL'


export const ROOM_CATEGORIES_LIST_REQUEST = 'ROOM_CATGORIES_REQUEST_SUCCESS'
export const ROOM_CATEGORIES_LIST_SUCCESS = 'ROOM_CATGORIES_LIST_SUCCESS'
export const ROOM_CATEGORIES_LIST_FAIL = 'ROOM_CATGORIES_LIST_FAIL'
