export const FORGET_PASSWORD_REQUEST = 'FORGET_PASSWORD_REQUEST'
export const FORGET_PASSWORD_SUCCESS = 'FORGET_PASSWORD_SUCCESS'
export const FORGET_PASSWORD_SUCCESS_CATCH_EMAIL = 'FORGET_PASSWORD_SUCCESS_CATCH_EMAIL'

export const FORGET_PASSWORD_FAIL = 'FORGET_PASSWORD_FAIL' 


export const RESET_PASSWORD_REQUEST = 'RESET_PASSWORD_REQUEST'
export const RESET_PASSWORD_SUCCESS = 'RESET_PASSWORD_SUCCESS'
export const RESET_PASSWORD_FAIL = 'RESET_PASSWORD_FAIL' 
export const FORGET_PASSWORD_RESET = 'FORGET_PASSWORD_RESET'

