export const SUBCATEGORY_ITEMS_LIST_REQUEST = 'SUBCATEGORY_ITEMS_LIST_REQUEST'
export const SUBCATEGORY_ITEMS_LIST_SUCCESS = 'SUBCATEGORY_ITEMS_LIST_SUCCESS'
export const SUBCATEGORY_ITEMS_LIST_FAIL = 'SUBCATEGORY_ITEMS_LIST_FAIL'


export const CATEGORY_ITEMS_LIST_REQUEST = 'CATEGORY_ITEMS_LIST_REQUEST'
export const CATEGORY_ITEMS_LIST_SUCCESS = 'CATEGORY_ITEMS_LIST_SUCCESS'
export const CATEGORY_ITEMS_LIST_FAIL = 'CATEGORY_ITEMS_LIST_FAIL'


